repos:
  - repo: local
    hooks:
      - id: ocamlformat
        name: ocamlformat check
        entry: make format-check
        language: system
        files: \.(ml|mli)$
        pass_filenames: false
        stages: [pre-push]
