(library
 (name opentelemetry_client_lwt)
 (public_name opentelemetry-client.lwt)
 (flags
  :standard
  -open
  Opentelemetry_util
  -open
  Opentelemetry_client
  -open
  Opentelemetry_atomic)
 (modules :standard \ gen_types_)
 (optional) ; lwt
 (libraries
  opentelemetry.util
  opentelemetry.atomic
  opentelemetry.emitter
  (re_export opentelemetry.core)
  (re_export opentelemetry)
  (re_export opentelemetry.ambient-context)
  ambient-context-lwt
  (re_export opentelemetry-client)
  (re_export lwt)
  threads
  mtime
  mtime.clock.os
  lwt.unix)
 (synopsis "Lwt-specific helpers for opentelemetry-client"))

(executable
 (name gen_types_)
 (modules gen_types_))

(rule
 (enabled_if %{lib-available:lwt})
 (deps types_.ml.5 types_.ml.6)
 (target types_.ml)
 (action
  (run ./gen_types_.exe %{version:lwt})))
