name: github pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/ocaml-tracing/ocaml-opentelemetry/ci-5.4:latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          submodules: recursive

      - name: Install local packages
        run: opam exec -- dune build @install && opam exec -- dune install

      - name: Build documentation
        run: |
          opam exec -- odig odoc --cache-dir=_doc/ \
            opentelemetry opentelemetry-client opentelemetry-lwt \
            opentelemetry-cohttp-lwt opentelemetry-client-ocurl \
            opentelemetry-client-ocurl-lwt opentelemetry-client-cohttp-lwt \
            opentelemetry-client-cohttp-eio opentelemetry-logs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_doc/html
          enable_jekyll: false
